update many packages
pnpm/meta-updater pull request #14
Opened 2024-05-09 02:01 UTC by altsalt

After exploring why a package deprecation kept popping up, I followed the thread to this project and noticed that it had been some time since anyone had run `pnpm up --latest`. I've done that and gotten `pnpm test` to run without complaint.

Figured there were enough changes to warrant a major semver bump. Unsure if there are other contribution guidelines or suggestions, so opening a PR for review.

Alas the original warning is still popping up, but that's further upstream...

2024-05-09 22:16 UTC, altsalt commented
Note that I finally found (and hopefully fixed) the initial warning that started me down this path in https://github.com/pnpm/pnpm/pull/8068

Also worth noting is that if/when this PR is accepted, https://github.com/altsalt/pnpm/blob/fd6cd2781716dd6c020474beae2f3a3da8493e6b/package.json#L23 will need to be updated to remove the forced Node16 installation (that does not work under NixOS).

2024-05-23 16:54 UTC, altsalt commented
Could you please review this @zkochan ? Don't want to be an annoyance, but would generally like to avoid pulling in so many outdated packages.

2024-06-12 01:10 UTC, zkochan approved these changes

2024-06-12 01:11 UTC, zkochan requested changes
The tests don't seem to pass.

2024-06-12 01:19 UTC, zkochan approved these changes

2024-06-12 01:20 UTC, merged